global:
  scrape_interval: 15s  # How often Prometheus will scrape the endpoint

scrape_configs:
  - job_name: 'pricing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
